### ISSUE TITLE
slim-scroll scroll bar is not showing when using ng-repeat

### ISSUE THREAD

**Issue by karthick678** [kamlekar/slim-scroll#15]
slim-scroll scroll bar is not showing when using ng-repeat

**Comment by kamlekar** [comment]
Please give more details. may be a fiddle so that I can say something. AFAIK, this should work irrespective of ng-repeat or anything else.

**Comment by BDominik** [comment]
Not showing at me to. :(
But I think that slimscroll cant get the height of the parent container and than the scroll bar get display:none; and height of the container.
If put to display:block; and add height:25px; itt will work, in my case.
Sorry for my bad english.

**Comment by kamlekar** [comment]
@BDominik please provide a simple test fiddle so that I can help you.

**Comment by BDominik** [comment]
Hi.
I actually used ng-slimscroll from this site.
https://www.npmjs.com/package/ng-slimscroll
Not your version. But i think the promblem might be the same with booth
<ul class="items_holder " ng-slimscroll width="100%">
      <li ng-repeat="logs in loginLogs">
            {{logs.email}}
            <span class="pull-right value">{{formatDate(logs.created) | amCalendar }}</span>
      </li>
</ul>
.items_holder div{
	display: block !important;
	height:25px !important;
}
Its helped for me.

**Comment by acivan** [comment]
This is really a problem.

**Comment by kamlekar** [comment]
@acivan  Hey can you please create a simple test fiddle to show the issue? I am good with JavaScript but not related frameworks like AngularJS. A fiddle help me a lot. Thanks.

**Comment by kamlekar** [comment]
Closing this ticket as there is no reply for long time.
