### ISSUE TITLE
resetValues() breaks scrolling with scroll wheel and arrow keys

### ISSUE THREAD

**Issue by nstoddard** [kamlekar/slim-scroll#25]
On the [demo page](https://rawgit.com/venkateshwar/slim-scroll/master/test/index.html), if I resize the window, scrolling no longer works with the scroll wheel or arrow keys (it scrolls the entire page instead). Clicking and dragging the scrollbar itself still works. This seems to be due to the call to resetValues().

I'm using Chrome, on Windows 7.

**Comment by kamlekar** [comment]
Yes, thanks for this bug. If possible please PR this.
