### ISSUE TITLE
Help add package.json to upstream

### ISSUE THREAD

**Issue by sufuf3** [kamlekar/slim-scroll#27]
Hi @kamlekar, 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We hosted this library.
Could you please help me add `package.json` to upstream?
Thank you.

[cdnjs/cdnjs#10469](https://github.com/cdnjs/cdnjs/pull/10469)

**Comment by kamlekar** [comment]
Thank you and yes @sufuf3, I can help. What I should keep in that package.json file?

**Comment by sufuf3** [comment]
You can refer to this website: https://docs.npmjs.com/files/package.json
Thank you.

**Comment by kamlekar** [comment]
Hi @sufuf3 Thanks for the link. I have added package.json. Hope it is fine now.

**Comment by sufuf3** [comment]
Thank you for your help.
