### ISSUE TITLE
Does not work with textarea

### ISSUE THREAD

**Issue by vishalmane** [kamlekar/slim-scroll#28]
I tried to use it with text area but it was not showing scroll

**Comment by kamlekar** [comment]
Could you please provide a fiddle?

**Comment by FizzyGalacticus** [comment]
[Here](https://codepen.io/FizzyGalacticus/pen/WEjPdY?editors=1111) is a Codepen of the same issue. Please let us know if you find a resolution!

**Comment by kamlekar** [comment]
@FizzyGalacticus Though I haven't checked the fiddle ( on mobile), I can guess that this plug in wasn't created to work with textarea because we can't have child elements under textarea to replicate the scrollbar.
