### ISSUE TITLE
No npm module or cdn?

### ISSUE THREAD

**Issue by Right2Drive** [kamlekar/slim-scroll#29]
Is there no npm module or CDN host for this? And if there is can you add to README?

**Comment by kamlekar** [comment]
Hi, this plugin is now available on CDNjs. Here is the link

[https://cdnjs.com/libraries/slim-scroll](https://cdnjs.com/libraries/slim-scroll).

Thanks!!

**Comment by Right2Drive** [comment]
Awesome thanks!
