### ISSUE TITLE
TypeError: e.removeProp is not a function  slimscroll.min.js:1:2231

### ISSUE THREAD

**Issue by ShantaramTupe** [kamlekar/slim-scroll#31]
I tried using 
```jquery
new slimScroll('.my-class');
```
I got error 
**TypeError: e.removeProp is not a function[Learn More]  slimscroll.min.js:1:2231**

**Comment by kamlekar** [comment]
Hi @ShantaramTupe,

You should provide DOM object instead of string as argument. Please check this [line](https://github.com/kamlekar/slim-scroll#method-1-with-no-added-styles).

**Comment by ShantaramTupe** [comment]
**No success I use your initialization process**
```javascript
    var element = document.querySelectorAll('.element-class');
    var one = new slimScroll(element[0], {
        'wrapperClass': 'scroll-wrapper unselectable mac',
        'scrollBarContainerClass': 'scrollBarContainer',
        'scrollBarContainerSpecialClass': 'animate',
        'scrollBarClass': 'scroll',
        'keepFocus': true
    });
```
**also tried this** 

```javascript
    var element = document.querySelector('#element-id');
    var one = new slimScroll(element, {
        'wrapperClass': 'scroll-wrapper unselectable mac',
        'scrollBarContainerClass': 'scrollBarContainer',
        'scrollBarContainerSpecialClass': 'animate',
        'scrollBarClass': 'scroll',
        'keepFocus': true
    });
```

**Comment by kamlekar** [comment]
Hi @ShantaramTupe, If the element's parent div is hidden then you can't access the child like this. I am pretty sure that is the issue here.

**Comment by ShantaramTupe** [comment]
@kamlekar I have put above mentioned code after my `slideToggle()` function completes (i.e. when I display my div)
but getting same error as **TypeError: e.removeProp is not a function slimscroll.min.js:1:2231**

**Comment by kamlekar** [comment]
@ShantaramTupe Can you please create a simple fiddle? So that I can look through quickly and help you.

**Comment by kamlekar** [comment]
Hi @ShantaramTupe 

Any update? 

I will reopen this issue. I will close this, If there is no reply for longer period.

**Comment by kamlekar** [comment]
Closing this ticket as there is no reply.
